import React from "react"

import { RootClientLayout } from "./clientLayout"

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
    return (
        <html lang="en">
            <body>
                <RootClientLayout>{children}</RootClientLayout>
            </body>
        </html>
    )
}
